<?php

namespace App\Http\Controllers\Admin;
use App\Http\Requests\Admin\CreateUpdateMealeRequest;
use App\Models\Meal;
use Illuminate\Http\Request;

class MealsController extends BaseController
{

    protected $modelClass = Meal::class;
    protected $title = 'الوجبات';
    protected $route = 'meals';

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    function show(Meal $meal)
    {
        return redirect()->back()->with('msg','لا يوجد تفاصيل');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUpdateMealeRequest $request)
    {
        //
        return $this->saveData($request->validated());
    }


    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Meal $meal
     * @return \Illuminate\Http\Response
     */
    public function update(CreateUpdateMealeRequest $request, Meal $meal)
    {
        //
        return $this->saveData($request->validated(), $meal);
    }

    public function saveData($data, $item = null)
    {
        unset($data['image']);
        if (\request()->image) {
            $name = \request()->image->store("original");
            $imgName = resize_image($name);
            if ($imgName)
                $data['image'] = $imgName;
        }
        return parent::saveData($data, $item); // TODO: Change the autogenerated stub
    }

}
